name: Create a repository dispatch for Kaiserreich/Kaiserreich-4-GFX-Search
on:
  push:
    branches:
    - master
    paths:
    - 'gfx/texticons/**/*.dds'
    - 'gfx/texticons/**/*.tga'
    - 'gfx/event_pictures/**/*.dds'
    - 'gfx/event_pictures/**/*.tga'
    - 'gfx/event_news_pictures/**/*.dds'
    - 'gfx/event_news_pictures/**/*.tga'
    - 'gfx/interface/decisions/**/*.dds'
    - 'gfx/interface/decisions/**/*.tga'
    - 'gfx/interface/goals/**/*.dds'
    - 'gfx/interface/ideas/**/*.dds'
    - 'gfx/interface/goals/**/*.tga'
    - 'gfx/interface/ideas/**/*.tga'
    - 'gfx/interface/operatives/agencies/**/*.dds'
    - 'gfx/interface/operatives/agencies/**/*.tga'
    - 'interface/**/*.gfx'
    - 'interface/*.gfx'

jobs:
  gfx_search_dispatch:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ICON_DISPATCH_TOKEN }}
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Get changed files
      run: |
        BEFORE=$(cat $GITHUB_EVENT_PATH | python -c "import sys, json; print(json.load(sys.stdin)['before'])")
        MODIFIED_FILES=""
        MODIFIED_FILES=$(curl -u "antoni.baum@protonmail.com:${GITHUB_TOKEN}" -s https://api.github.com/repos/$GITHUB_REPOSITORY/compare/$BEFORE...$GITHUB_SHA | python -c "import sys, json; files = json.load(sys.stdin)['files']; print(repr(' '.join([repr(x['filename']) for x in files])))" 2>/dev/null)
        export MODIFIED_FILES
        echo "MODIFIED_FILES=$MODIFIED_FILES" >> $GITHUB_ENV
        echo $MODIFIED_FILES
    - name: Create Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ICON_DISPATCH_TOKEN }}
        repository: Kaiserreich/Kaiserreich-4-GFX-Search
        event-type: update-page
        client-payload: '{"files": ${{ env.MODIFIED_FILES }}}'
